=== milosrasevic/xml-papersapp/src/main/resources/data/SciencePaper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.tim12.com/science_paper"
    xmlns:sp="http://www.tim12.com/science_paper">
    <xs:element name="SciencePaper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="preserve"/>
                            <xs:pattern value=".+(\s.+){0,15}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="authors" type="sp:TAuthors"> </xs:element>
                <xs:element name="reviewers" type="sp:TReviewers"> </xs:element>
                <xs:element name="content" type="sp:TContent"> </xs:element>
                <xs:element name="abstract" type="sp:TAbstract"> </xs:element>
                <xs:element name="references" type="sp:TReferences"> </xs:element>
            </xs:sequence>
            <xs:attribute name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=""/>
                        <xs:pattern value="http://www.tim12.com/science_paper/.+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dateCreated" type="xs:date"/>
            <xs:attribute name="dateRevised" type="xs:date"/>
            <xs:attribute name="dateAccepted" type="xs:date"/>
            <xs:attribute name="dateRejected" type="xs:date"/>
            <xs:attribute name="state" type="sp:TState"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TState">
        <xs:restriction base="xs:string">
            <xs:enumeration value="waiting"/>
            <xs:enumeration value="review_in_progress"/>
            <xs:enumeration value="rejected"/>
            <xs:enumeration value="accepted"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="waiting_for_approval"/>
            <xs:enumeration value="revision_needed"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TAuthors">
        <xs:sequence maxOccurs="unbounded" minOccurs="1">
            <xs:element name="author" type="sp:TAuthor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAuthor">
        <xs:sequence>
            <xs:element name="firstName" default="" nillable="false" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="profession" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TReviewers">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="reviewer" type="sp:TAuthor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAbstract">
        <xs:sequence>
            <xs:element name="purpose" type="xs:string"/>
            <xs:element name="findings" type="xs:string"/>
            <xs:element name="designMethodologyApproach" type="xs:string"/>
            <xs:element name="researchLimitationsAndImplications" type="xs:string"/>
            <xs:element name="practicalImplications" type="xs:string"/>
            <xs:element name="socialImlications" type="xs:string"/>
            <xs:element name="originalityAndValue" type="xs:string"/>
            <xs:element name="keywords">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="12" name="Kljucna_rec" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="type" type="sp:TType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="research_paper"/>
            <xs:enumeration value="viewpoint"/>
            <xs:enumeration value="technical_paper"/>
            <xs:enumeration value="conceptual_paper"/>
            <xs:enumeration value="case_study"/>
            <xs:enumeration value="literature_review"/>
            <xs:enumeration value="general_review"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TContent">
        <xs:sequence>
            <xs:element name="section" type="sp:TSection" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TReferences">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="Referenca" type="sp:TReference"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TTable">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="row" type="sp:TRow"/>
        </xs:sequence>
        <xs:attribute name="id">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                        value="http://www.tim12.com/naucni_rad/poglavlje/\d+/pasus/\d+/slika/\d+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TRow">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="cell" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPicture">
        <xs:attribute name="id">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                        value="http://www.tim12.com/naucni_rad/poglavlje/\d+/pasus/\d+/slika/\d+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="url" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="TSection" block="">
        <xs:sequence>
            <xs:element name="title">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="Id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="http://www.tim12.com/naucni_rad/\d+/poglavlje/\d+/naslov"
                                        />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" name="paragraph" type="sp:TParagraph"/>
        </xs:sequence>
        <xs:attribute name="id">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="http://www.tim12.com/naucni_rad/\d+/poglavlje/\d+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType mixed="true" name="TParagraph">
        <xs:choice maxOccurs="unbounded">
            <xs:element maxOccurs="1" minOccurs="0" name="table" type="sp:TTable"> </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="picture" type="sp:TPicture"> </xs:element>
        </xs:choice>
        <xs:attribute name="Id">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="http://www.tim12.com/naucni_rad/\d+/poglavlje/\d+/pasus/\d+"/>
                    <xs:pattern value=""/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TReference">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="type" type="sp:TReferenceType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TReferenceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="book"/>
            <xs:enumeration value="book_chapter"/>
            <xs:enumeration value="journal"/>
            <xs:enumeration value="published_conference_proceeding"/>
            <xs:enumeration value="unpublished_conference_proceeding"/>
            <xs:enumeration value="working_paper"/>
            <xs:enumeration value="encyclopedia"/>
            <xs:enumeration value="newspaper_article_authored"/>
            <xs:enumeration value="newspaper_article_unauthored"/>
            <xs:enumeration value="electronic_source"/>
            <xs:enumeration value="data"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== milosrasevic/xml-papersapp/src/main/resources/data/science_paper.xml
<?xml version="1.0" encoding="UTF-8"?>
<sp:SciencePaper xmlns:os="http://www.tim12.com/user"
 xmlns:sp="http://www.tim12.com/science_paper"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tim12.com/science_paper file:/home/classicdocs/Documents/Workspace/xml/xml-papersapp/src/main/resources/data/SciencePaper.xsd">
    <sp:title>title0</sp:title>
    <sp:authors>
        <sp:author>
            <os:firstName>firstName0</os:firstName>
            <os:lastName>lastName0</os:lastName>
            <os:profession>profession0</os:profession>
            <os:phoneNumber>000-000-0000</os:phoneNumber>
            <os:email>0@00.AA</os:email>
            <os:role>editor</os:role>
        </sp:author>
        <sp:author>
            <os:firstName>firstName1</os:firstName>
            <os:lastName>lastName1</os:lastName>
            <os:profession>profession1</os:profession>
            <os:phoneNumber>000-000-0000</os:phoneNumber>
            <os:email>0@00.AA</os:email>
            <os:role>editor</os:role>
        </sp:author>
    </sp:authors>
    <sp:reviewers>
    </sp:reviewers>
    <sp:content>
        <sp:section>
            <sp:title>title1</sp:title>
            <sp:paragraph>
            </sp:paragraph>
            <sp:paragraph>
            </sp:paragraph>
        </sp:section>
        <sp:section>
            <sp:title>title2</sp:title>
            <sp:paragraph>
            </sp:paragraph>
            <sp:paragraph>
            </sp:paragraph>
        </sp:section>
    </sp:content>
    <sp:abstract>
        <sp:purpose>purpose0</sp:purpose>
        <sp:findings>findings0</sp:findings>
        <sp:designMethodologyApproach>designMethodologyApproach0</sp:designMethodologyApproach>
        <sp:researchLimitationsAndImplications>researchLimitationsAndImplications0</sp:researchLimitationsAndImplications>
        <sp:practicalImplications>practicalImplications0</sp:practicalImplications>
        <sp:socialImlications>socialImlications0</sp:socialImlications>
        <sp:originalityAndValue>originalityAndValue0</sp:originalityAndValue>
        <sp:keywords>
            <sp:Kljucna_rec>Kljucna_rec0</sp:Kljucna_rec>
            <sp:Kljucna_rec>Kljucna_rec1</sp:Kljucna_rec>
        </sp:keywords>
        <sp:type>research_paper</sp:type>
    </sp:abstract>
    <sp:references>
        <sp:Referenca>
            <sp:name>name0</sp:name>
            <sp:type>book</sp:type>
        </sp:Referenca>
        <sp:Referenca>
            <sp:name>name1</sp:name>
            <sp:type>book</sp:type>
        </sp:Referenca>
    </sp:references>
</sp:SciencePaper>

=== milosrasevic/xml-papersapp/src/main/resources/data/sp1.xml
<?xml version="1.0" encoding="UTF-8"?>
<SciencePaper xmlns="http://www.tim12.com/science_paper"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tim12.com/science_paper file:/home/classicdocs/Documents/Workspace/xml/xml-papersapp/src/main/resources/data/SciencePaper.xsd">
    <title>title0</title>
    <authors>
        <author>
            <firstName>firstName0</firstName>
            <email>author1@gmail.com</email>
            <lastName>lastName0</lastName>
            <profession>profession0</profession>
        </author>
        <author>
            <firstName>firstName1</firstName>
            <email>author2@gmail.com</email>
            <lastName>lastName1</lastName>
            <profession>profession1</profession>
        </author>
    </authors>
    <reviewers>
    </reviewers>
    <content>
        <section>
            <title>title1</title>
            <paragraph>
            </paragraph>
            <paragraph>
            </paragraph>
        </section>
        <section>
            <title>title2</title>
            <paragraph>
            </paragraph>
            <paragraph>
            </paragraph>
        </section>
    </content>
    <abstract>
        <purpose>purpose0</purpose>
        <findings>findings0</findings>
        <designMethodologyApproach>designMethodologyApproach0</designMethodologyApproach>
        <researchLimitationsAndImplications>researchLimitationsAndImplications0</researchLimitationsAndImplications>
        <practicalImplications>practicalImplications0</practicalImplications>
        <socialImlications>socialImlications0</socialImlications>
        <originalityAndValue>originalityAndValue0</originalityAndValue>
        <keywords>
            <Kljucna_rec>Kljucna_rec0</Kljucna_rec>
            <Kljucna_rec>Kljucna_rec1</Kljucna_rec>
        </keywords>
        <type>research_paper</type>
    </abstract>
    <references>
        <Referenca>
            <name>name0</name>
            <type>book</type>
        </Referenca>
        <Referenca>
            <name>name1</name>
            <type>book</type>
        </Referenca>
    </references>
</SciencePaper>
